# Generated by Django 6.0.3 on 2026-03-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4')], max_length=1)),
                ('category', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('notes', 'Notes'), ('exam', 'Exam Paper'), ('video', 'Video Link')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='notes/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
